### PR TITLE
add hammer to platform minigame

### PR DESCRIPTION
**Pull request by plsplsplslol**

### CODE REVIEW

**Comment by l-ouis** [comment]
dont accept
its a keylogger

**Comment by headshot2017** [comment]
i don't know... the timer is already MS away from ending by the time you land on the platform, why not make this a config in src/game/variables.h?

**Comment by l-ouis** [comment]
with large players, people spamming hammer at the beginning will send everyone flying up to fail

**Comment by headshot2017** [comment]
to be honest i agree with louis, you can somewhat troll players to an extent on the flood (get on a platform) microgame by hammering them (and you can fight back or defend yourself by hooking the ground), but in this case, more players or even possibly everyone would be more focused on hammering each other instead of completing the objective, not to mention the platform is unhookable.

**Pull request closed without merging**
